version: '2'
services:
  http-uptime-checker:
    image: shalb/http-uptime-checker:0.0.1
   #volumes:
   #  - ./entrypoint:/opt/entrypoint
    restart: always
   #ports:
   #  - "8000:8000"
    environment:
      - TARGET_URL=https://example.com
      - TARGET_URL_CHECK_INTERVAL=6
      - FAILS_TO_DOWNTIME=5
      - LOG_LEVEL=INFO

